FROM rust:1.96.0 AS builder

WORKDIR /app
COPY Cargo.toml Cargo.lock ./
COPY src ./src
COPY migrations ./migrations

RUN cargo build --bin migrate

FROM debian:bookworm-slim

WORKDIR /app
COPY --from=builder /app/target/debug/migrate .

CMD ["./migrate"]